#!/data/data/com.termux/files/usr/bin/bash
############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'


cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'
gri='\e[2m'
#----------------

fin='\033[01;37m'
############3


# clxx="$(sh /xg/0r/.betas/i/colorr)"
# c00l="$(sh /xg/0r/.betas/i/color)"
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
#   diasem="$(date +%A)"
#   mes="$(date +%B)"
#   diafech="$(date +%e)"
#   ttime="$(date +'%I:%M')"
#   ye="$(date +%Y)"
######################################

#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#   ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#   ant3=`netstat -r | grep "default" | awk {'print $8'}`
#   nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#   routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################



inici0 () {
	echo ""

	cd /data/data/com.termux/files/usr/etc
	rm -f motd

 rm -f  /data/data/com.termux/files/usr/etc/bash.bashrc  ;	cp /data/data/com.termux/files/home/t99/bash.bashrc /data/data/com.termux/files/usr/etc




pkg update -y
apt update -y


pkg install curl  -y

apt install toilet -y

apt install cmatrix -y 
apt install bash-completion -y
apt install tree -y 
apt install nginx -y

pkg install nano nmap -y
pkg install wget -y 
#pkg install git -y

pkg install python -y 
pkg install python3 -y

python3 -m pip install --upgrade pip

pkg i ffmpeg -y


pip install -U youtube_dl
pip install mpv
pkg install mpv -y
pkg i ffmpeg -y
pip install -U youtube_d


cd /data/data/com.termux/files/usr/etc/nginx
rm -f nginx.conf
cd
cd t99 
mv nginx.conf /data/data/com.termux/files/usr/etc/nginx
mv 99 /data/data/com.termux/files/home
	cd
	termux-setup-storage
} 

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################

#   if [ $varr = "1" ]; then
# clear
# 	 echo "
# 
# "
# else
# echo ""
# fi
inici0